server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://authentication-service:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: authentication-service-docs
          uri: http://authentication-service:8081
          predicates:
            - Path=/authentication-service/api-docs/**

        - id: user-service-docs
          uri: http://user-service:8082
          predicates:
            - Path=/user-service/api-docs/**

        - id: social-graph-service-docs
          uri: http://social-graph-service:8083
          predicates:
            - Path=/social-graph-service/api-docs/**

        - id: post-service-docs
          uri: http://post-service:8084
          predicates:
            - Path=/post-service/api-docs/**

        - id: timeline-service-docs
          uri: http://timeline-service:8085
          predicates:
            - Path=/timeline-service/api-docs/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/users/**
          filters:
            - Authentication

        - id: social-graph-service
          uri: http://social-graph-service:8083
          predicates:
            - Path=/api/v1/social-graph/**
          filters:
            - Authentication

        - id: post-service
          uri: http://post-service:8084
          predicates:
            - Path=/api/v1/post/**,/api/v1/posts/**,/api/v1/like/**,/api/v1/repost/**,/api/v1/reposts/**,/api/v1/reply/**,/api/v1/replies/**
          filters:
            - Authentication

        - id: timeline-service
          uri: http://timeline-service:8085
          predicates:
            - Path=/api/v1/timeline/**
          filters:
            - Authentication

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: post-service
        url: /post-service/api-docs

      - name: user-service
        url: /user-service/api-docs

      - name: social-graph-service
        url: /social-graph-service/api-docs

      - name: authentication-service
        url: /authentication-service/api-docs

      - name: timeline-service
        url: /timeline-service/api-docs

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

services:
  auth:
    name: authentication-service
