db:
  username: test
  password: test

spring:
  datasource:
    username: test
    password: test
  jpa:
    properties.hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: test-group-id

eureka:
  client:
    enabled: false
