server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-authentication-service:5432/social-graph-service
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
