server:
  port: 0

spring:
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /timeline-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

services:
  user:
    name: user-service
  post:
    name: post-service
