server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  data:
    redis:
      host: redis
      port: 6379
