server:
  port: 8085

spring:
  application:
    name: timeline-service
  data:
    redis:
      cluster:
        nodes: redis-0.redis:6379,redis-1.redis:6379,redis-2.redis:6379,redis-3.redis:6379,redis-4.redis:6379,redis-5.redis:6379

springdoc:
  api-docs:
    path: /timeline-service/api-docs

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

services:
  social-graph:
    name: social-graph-service
    url: social-graph-service.default.svc.cluster.local:8083
  post:
    name: post-service
    url: post-service.default.svc.cluster.local:8084
