server:
  port: 0

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://postgres-authentication-service:5432/authentication-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /authentication-service/api-docs

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

services:
  user:
    name: user-service

secret:
  key: "AQCa9l1Zs2yhPiSfjIU9PYqGoXkuvSnfJhHdpa4pwnfg3AtKzNI4PCWHRTp+rNYk5sqHJY300XlYcWD2WAO5ONDoPAQbR/i+WN5+nMljv407rxMtyn8Fa/0e9ICII/OS9vB7x1l4kE0OKKBEJiEkdcbDQS+JfdJqRBV5HiQFQrjLpG525VddRkCbcW046Z1XlWQOaOrdDNP3hC8BWW8d+0AYTFdpIFrAeYQxpRf3dJWbEK2aUjxZUbHbgXlUiFkFhtaq22FpjKK9Vkl+TLhl1K0wTc54wPQD1Szb1Ap8UZRR5Vi1OArOCIRWeJvAKw5ktZmgKbBjfI34ba5m7VbiSrVDHBZxExNmk5mFK8nNx+vznMPOwcAn6sMRuXin4SPSbsUpvDAzR0hxJcfWnodxRMGWeFu76ctfykTTcxtmU0j7bVqYKK0ewTArATnR68PtF+4lCnaYHLMl99AxWNfza806"
